version: '3.8'
services:
  # Kong API Gateway in DB-less mode
  kong-dbless:
    image: 'kong/kong-gateway:latest'
    container_name: kong-dbless-readonly
    read_only: true
    restart: unless-stopped
    volumes:
      - ./declarative:/kong/declarative/
      - ./tmp_volume:/tmp
      - ./prefix_volume:/var/run/kong
    environment:
      KONG_PREFIX: /var/run/kong
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"   # Proxy
      - "8001:8001"   # Admin API

  # PostgreSQL Database
  postgres-db:
    image: postgres:18-alpine
    restart: always
    container_name: local_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ActiveMQ Artemis Message Queue
  artemis:
    image: apache/activemq-artemis:latest
    container_name: artemis-broker
    ports:
      - "61616:61616"   # Core protocol
      - "8161:8161"     # Web Console
    volumes:
      - artemis-data:/var/lib/artemis-instance

  # Hashicorp Vault
  vault:
    container_name: trial-vault
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_ADDR: http://0.0.0.0:8200
    ports:
      - "8175:8200"
    volumes:
      - vault_data:/vault/data

volumes:
  postgres_data: {}
  artemis-data: {}
  vault_data: {}