services:
  vault:
    container_name: "trial-vault"
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_ADDR: "http://0.0.0.0:8200"
    ports:
      - "8175:8200"
    networks:
      - vaultnet    
    volumes:
          - vault_data:/vault/data

networks:
  vaultnet:
    name: vaultnet

volumes:
  vault_data:
    driver: local